sudo: false
language: node_js
node_js:
  - "5"
  - "node"

cache:
  directories:
    - node_modules

install:
- npm install

script:
- npm run lint
- npm run build
- npm run test
- npm run cover
- npm run codecov

os:
  - osx
