sudo: false
language: node_js
node_js:
  - "5"
  - "node"

env:
  global:
    - CODECOV_TOKEN: f0a0b002-8fa2-494c-a84b-fecfd62c5ca6

cache:
  directories:
    - node_modules

install:
- npm install
- npm install -g codecov

script:
- npm run lint
- npm run build
- npm run test
- npm run cover
- codecov

os:
  - osx
